---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    hostname: audiobookshelf
    user: 1000:1000
    ports:
      - 80:80
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - ./data/config:/config
      - ./data/metadata:/metadata
      - ./data/media/audiobooks:/audiobooks
      - ./data/media/podcasts:/podcasts
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://localhost/ping -O /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped
