up:
	clear
	@mkdir -p ./data/{config,metadata,media/{audiobooks,podcasts}}
	@docker-compose up -d

down:
	clear
	@docker-compose down

restart:
	clear
	@docker-compose restart

ps:
	clear
	@docker-compose ps

logs:
	clear
	@docker-compose logs -f
