up:
	clear
	@mkdir -p ./data/client
	@docker-compose up -d

down:
	clear
	@docker-compose down

restart:
	clear
	@docker-compose restart

ps:
	clear
	@docker-compose ps

console:
	clear
	@docker exec -it mongodb mongosh

logs:
	clear
	@docker-compose logs -f
