up:
	clear
	@mkdir -p ./data/es01 ./data/es02 ./data/es03
	@docker-compose up -d

down:
	clear
	@docker-compose down

restart:
	clear
	@docker-compose restart

ps:
	clear
	@docker-compose ps

logs:
	clear
	@docker-compose logs -f
