version: '3.7'

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    user: 1000:1000
    ports:
      - 80:4533
    environment:
      ND_MUSICFOLDER: /music
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      #ND_BASEURL: ""
    volumes:
      - ./data/config:/data
      - ./data/media:/music:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:4533/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
